In [17]:
import pandas as pd
df=pd.read_csv(r'IPL_Ball_by_Ball_2008_2022.csv')
match=pd.read_csv(r'IPL_Matches_2008_2022.csv')
len(df)
match['Venue']=match['Venue'].str.replace('MA Chidambaram Stadium, Chepauk, Chennai','MA Chidambaram Stadium')
match['Venue']=match['Venue'].str.replace('Wankhede Stadium, Mumbai','Wankhede Stadium')

match['Venue']=match['Venue'].str.replace('Eden Gardens, Kolkata','Eden Gardens')

match['Venue']=match['Venue'].str.replace('Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association Stadium, Mohali')
match['Venue']=match['Venue'].str.replace('Punjab Cricket Association IS Bindra Stadium','Punjab Cricket Association Stadium, Mohali')

match['Venue']=match['Venue'].str.replace('Arun Jaitley Stadium, Delhi','Arun Jaitley Stadium')
match['Venue']=match['Venue'].str.replace('Rajiv Gandhi International Stadium','Rajiv Gandhi International Stadium, Hyderabad')

match['Venue']=match['Venue'].str.replace('Rajiv Gandhi International Stadium, Hyderabad, Uppal','Rajiv Gandhi International Stadium, Hyderabad')


match['Venue']=match['Venue'].str.replace('M.Chinnaswamy Stadium','M Chinnaswamy Stadium')
match['Venue']=match['Venue'].str.replace('MA Chidambaram Stadium, Chepauk','MA Chidambaram Stadium')
match=match[match['method']!='D/L']
match=match[match['WonBy']!='NoResults']
merged_df = pd.merge(df,match, on='ID')

final= merged_df[['ID','Date','innings','overs','ballnumber','batter','bowler','non-striker','batsman_run','extras_run','BattingTeam','Team1','Team2','Season','Venue','Team1Players','Team2Players']]
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222374 entries, 0 to 222373
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222374 non-null  int64
 1   Date          222374 non-null  object
 2   innings       222374 non-null  int64
 3   overs         222374 non-null  int64
 4   ballnumber    222374 non-null  int64
 5   batter        222374 non-null  object
 6   bowler        222374 non-null  object
 7   non-striker   222374 non-null  object
 8   batsman_run   222374 non-null  int64
 9   extras_run    222374 non-null  int64
 10  BattingTeam   222374 non-null  object
 11  Team1         222374 non-null  object
 12  Team2         222374 non-null  object
 13  Season        222374 non-null  object
 14  Venue         222374 non-null  object
 15  Team1Players  222374 non-null  object
 16  Team2Players  222374 non-null  object
dtypes: int64(6), object(11)
memory usage: 28.8+ MB

In [18]:
import pandas as pd
df=pd.read_csv(r'IPL_Ball_by_Ball_2008_2022.csv')

In [19]:
final=final[final['innings']<3]

In [20]:
final['BattingTeam']=final['BattingTeam'].str.replace('Daredevils','Capitals')
final['BattingTeam']=final['BattingTeam'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
final['BattingTeam']=final['BattingTeam'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
final['BattingTeam']=final['BattingTeam'].str.replace('Kings XI Punjab','Punjab Kings')

final['Team1']=final['Team1'].str.replace('Daredevils','Capitals')
final['Team1']=final['Team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
final['Team1']=final['Team1'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
final['Team1']=final['Team1'].str.replace('Kings XI Punjab','Punjab Kings')

final['Team2']=final['Team2'].str.replace('Daredevils','Capitals')
final['Team2']=final['Team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
final['Team2']=final['Team2'].str.replace('Rising Pune Supergiants','Rising Pune Supergiant')
final['Team2']=final['Team2'].str.replace('Kings XI Punjab','Punjab Kings')
df=final

df=df[df['BattingTeam']!='Pune Warriors']
df=df[df['BattingTeam']!='Gujarat Lions']
df=df[df['BattingTeam']!='Kochi Tuskers Kerala']
df=df[df['BattingTeam']!='Rising Pune Supergiant']

df['BattingTeam'].unique()

array(['Rajasthan Royals', 'Gujarat Titans',
       'Royal Challengers Bangalore', 'Lucknow Super Giants',
       'Sunrisers Hyderabad', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders'],
      dtype=object)

In [21]:
final=final[final['overs']<6]
df=df[df['overs']<6]

In [22]:
import numpy as np

piv=pd.pivot_table(df, values =['batsman_run','extras_run'],index=['ID','innings','BattingTeam','Team1','Team2','Venue','Season'],
                         aggfunc = np.sum)
piv

                                                                                                                                                  batsman_run
ID      innings BattingTeam                 Team1                       Team2                 Venue                                      Season
335982  1       Kolkata Knight Riders       Royal Challengers Bangalore Kolkata Knight Riders M Chinnaswamy Stadium                      2007/08           51  \
        2       Royal Challengers Bangalore Royal Challengers Bangalore Kolkata Knight Riders M Chinnaswamy Stadium                      2007/08           19
335983  1       Chennai Super Kings         Punjab Kings                Chennai Super Kings   Punjab Cricket Association Stadium, Mohali 2007/08           50
        2       Punjab Kings                Punjab Kings                Chennai Super Kings   Punjab Cricket Association Stadium, Mohali 2007/08           61
335984  1       Rajasthan Royals            Delhi Capitals              Rajasthan Royals      Feroz Shah Kotla                           2007/08           38
...                                                                                                                                                       ...
1312198 2       Lucknow Super Giants        Royal Challengers Bangalore Lucknow Super Giants  Eden Gardens                               2022              55
1312199 1       Royal Challengers Bangalore Royal Challengers Bangalore Rajasthan Royals      Narendra Modi Stadium, Ahmedabad           2022              38
        2       Rajasthan Royals            Royal Challengers Bangalore Rajasthan Royals      Narendra Modi Stadium, Ahmedabad           2022              67
1312200 1       Rajasthan Royals            Rajasthan Royals            Gujarat Titans        Narendra Modi Stadium, Ahmedabad           2022              43
        2       Gujarat Titans              Rajasthan Royals            Gujarat Titans        Narendra Modi Stadium, Ahmedabad           2022              24

                                                                                                                                                  extras_run
ID      innings BattingTeam                 Team1                       Team2                 Venue                                      Season
335982  1       Kolkata Knight Riders       Royal Challengers Bangalore Kolkata Knight Riders M Chinnaswamy Stadium                      2007/08          10
        2       Royal Challengers Bangalore Royal Challengers Bangalore Kolkata Knight Riders M Chinnaswamy Stadium                      2007/08           7
335983  1       Chennai Super Kings         Punjab Kings                Chennai Super Kings   Punjab Cricket Association Stadium, Mohali 2007/08           3
        2       Punjab Kings                Punjab Kings                Chennai Super Kings   Punjab Cricket Association Stadium, Mohali 2007/08           2
335984  1       Rajasthan Royals            Delhi Capitals              Rajasthan Royals      Feroz Shah Kotla                           2007/08           2
...                                                                                                                                                      ...
1312198 2       Lucknow Super Giants        Royal Challengers Bangalore Lucknow Super Giants  Eden Gardens                               2022              7
1312199 1       Royal Challengers Bangalore Royal Challengers Bangalore Rajasthan Royals      Narendra Modi Stadium, Ahmedabad           2022              8
        2       Rajasthan Royals            Royal Challengers Bangalore Rajasthan Royals      Narendra Modi Stadium, Ahmedabad           2022              0
1312200 1       Rajasthan Royals            Rajasthan Royals            Gujarat Titans        Narendra Modi Stadium, Ahmedabad           2022              1
        2       Gujarat Titans              Rajasthan Royals            Gujarat Titans        Narendra Modi Stadium, Ahmedabad           2022              7

[1739 rows x 2 columns]

In [23]:

piv['PP']=piv['extras_run']+piv['batsman_run']

piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv.reset_index(level=0, inplace=True)
piv

,Season,Venue,Team2,Team1,BattingTeam,innings,ID,batsman_run,extras_run,PP
0,2007/08,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,1,335982,51,10,61
1,2007/08,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,2,335982,19,7,26
2,2007/08,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Punjab Kings,Chennai Super Kings,1,335983,50,3,53
3,2007/08,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,Punjab Kings,Punjab Kings,2,335983,61,2,63
4,2007/08,Feroz Shah Kotla,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,1,335984,38,2,40
...,...,...,...,...,...,...,...,...,...,...
1734,2022,Eden Gardens,Lucknow Super Giants,Royal Challengers Bangalore,Lucknow Super Giants,2,1312198,55,7,62
1735,2022,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore,1,1312199,38,8,46
1736,2022,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,2,1312199,67,0,67
1737,2022,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,Rajasthan Royals,1,1312200,43,1,44
1738,2022,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Rajasthan Royals,Gujarat Titans,2,1312200,24,7,31

# Predicted score

In [10]:
import math
def bowler_strikerate(batsman,bowler):
    h=final[final['batter']==batsman] 
    h=h[h['extras_run']==0]
    h=h[h['bowler']==bowler]
    if h['batsman_run'].sum()==0:
        return 1.35
    elif len(h)!=0:
        return h['batsman_run'].sum()/len(h)
    else:
        return 1.35

def stadium_strikerate(batsman,venue):
    h=final[final['batter']==batsman] 
    h=h[h['extras_run']==0]
    for i in final['Venue'].unique():
        if venue in i:
            venue=i
        
    h=h[h['Venue']==venue]
    if h['batsman_run'].sum()==0:
        return 1.35
    elif len(h)!=0:
        return h['batsman_run'].sum()/len(h)
    else:
        return 1.35

def innings_strikerate(batsman,innings):
    h=final[final['batter']==batsman] 
    h=h[h['extras_run']==0]
    h=h[h['innings']==innings]
    if h['batsman_run'].sum()==0:
        return 1.35
    elif len(h)!=0:
        return h['batsman_run'].sum()/len(h)
    else:
        return 1.35
    

batsmen=['V Kohli','F du Plessis']
bowlers=['TA Boult','R Ashwin','Avesh Khan']


def score(batsmen,bowlers,venue,innings,battingteam,bowlingteam):
    strike=[]
    for i in batsmen:
        s=0
        for j in bowlers:
            s+=bowler_strikerate(i,j)
        a=stadium_strikerate(i,venue)
        b=innings_strikerate(i,innings)
        s/=len(bowlers)
        strike.append((0.3*a)+(0.65*s)+(0.05*b))
    for i in range(len(strike)):
        strike[i]*=36/len(batsmen)
    bat=piv
    tem=bat[(bat['BattingTeam']==battingteam) & (bat['Season']=='2022')]['PP'].mean()
    res=((sum(strike)*0.65+tem*0.35))+piv[(piv['BattingTeam']!=bowlingteam) & ((piv['Team1']==bowlingteam) | (piv['Team2']==bowlingteam))]['extras_run'].mean()
    return math.ceil(0.6*res+0.4*piv[(piv['BattingTeam']!=bowlingteam) & ((piv['Team1']==bowlingteam) | (piv['Team2']==bowlingteam)) & (piv['Season']=='2022')]['PP'].mean())

print(score(batsmen,bowlers,'M Chinnaswamy Stadium',2,'Royal Challengers Bangalore','Rajasthan Royals'))

44

In [11]:
for i in final['Venue'].unique():
    if 'Ed' in i:
        print(i)

Eden Gardens

In [12]:
max(piv[piv['BattingTeam']=='Kolkata Knight Riders']['PP'])

105

In [29]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69342 entries, 0 to 222310
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            69342 non-null  int64
 1   Date          69342 non-null  object
 2   innings       69342 non-null  int64
 3   overs         69342 non-null  int64
 4   ballnumber    69342 non-null  int64
 5   batter        69342 non-null  object
 6   bowler        69342 non-null  object
 7   non-striker   69342 non-null  object
 8   batsman_run   69342 non-null  int64
 9   extras_run    69342 non-null  int64
 10  BattingTeam   69342 non-null  object
 11  Team1         69342 non-null  object
 12  Team2         69342 non-null  object
 13  Season        69342 non-null  object
 14  Venue         69342 non-null  object
 15  Team1Players  69342 non-null  object
 16  Team2Players  69342 non-null  object
dtypes: int64(6), object(11)
memory usage: 9.5+ MB

In [32]:
final.Team1.unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Rising Pune Supergiant',
       'Gujarat Lions', 'Pune Warriors', 'Kochi Tuskers Kerala'],
      dtype=object)

In [13]:
df.head()

,ID,Date,innings,overs,ballnumber,batter,bowler,non-striker,batsman_run,extras_run,BattingTeam,Team1,Team2,Season,Venue,Team1Players,Team2Players
0,1312200,2022-05-29,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."
1,1312200,2022-05-29,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,0,1,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."
2,1312200,2022-05-29,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,1,0,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."
3,1312200,2022-05-29,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."
4,1312200,2022-05-29,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,0,0,Rajasthan Royals,Rajasthan Royals,Gujarat Titans,2022,"Narendra Modi Stadium, Ahmedabad","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan..."

In [14]:
bowler=df['bowler'].unique()
batsman=df['batter'].unique()
team=df['BattingTeam'].unique()

In [15]:
len(team)

10

In [16]:
team

array(['Rajasthan Royals', 'Gujarat Titans',
       'Royal Challengers Bangalore', 'Lucknow Super Giants',
       'Sunrisers Hyderabad', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders'],
      dtype=object)

In [27]:
import pickle

# Save necessary data and functions into a pickle file
with open('ipl_predictor_data.pkl', 'wb') as f:
    pickle.dump((final, piv, bowler_strikerate, stadium_strikerate, innings_strikerate, score), f)

In [28]:
with open('ipl_predictor_data.pkl', 'rb') as f:
    data = pickle.load(f)

In [29]:
data

(             ID        Date  innings  overs  ballnumber       batter  \
 0       1312200  2022-05-29        1      0           1  YBK Jaiswal
 1       1312200  2022-05-29        1      0           2  YBK Jaiswal
 2       1312200  2022-05-29        1      0           3   JC Buttler
 3       1312200  2022-05-29        1      0           4  YBK Jaiswal
 4       1312200  2022-05-29        1      0           5  YBK Jaiswal
 ...         ...         ...      ...    ...         ...          ...
 222306   335982  2008-04-18        2      5           2     W Jaffer
 222307   335982  2008-04-18        2      5           3   MV Boucher
 222308   335982  2008-04-18        2      5           4   MV Boucher
 222309   335982  2008-04-18        2      5           5     CL White
 222310   335982  2008-04-18        2      5           6   MV Boucher

                 bowler  non-striker  batsman_run  extras_run  \
 0       Mohammed Shami   JC Buttler            0           0
 1       Mohammed Shami   JC Buttler            0           1
 2       Mohammed Shami  YBK Jaiswal            1           0
 3       Mohammed Shami   JC Buttler            0           0
 4       Mohammed Shami   JC Buttler            0           0
 ...                ...          ...          ...         ...
 222306        AB Dinda     CL White            0           0
 222307        AB Dinda     CL White            0           0
 222308        AB Dinda     CL White            1           0
 222309        AB Dinda   MV Boucher            1           0
 222310        AB Dinda     CL White            0           0

                         BattingTeam                        Team1  \
 0                  Rajasthan Royals             Rajasthan Royals
 1                  Rajasthan Royals             Rajasthan Royals
 2                  Rajasthan Royals             Rajasthan Royals
 3                  Rajasthan Royals             Rajasthan Royals
 4                  Rajasthan Royals             Rajasthan Royals
 ...                             ...                          ...
 222306  Royal Challengers Bangalore  Royal Challengers Bangalore
 222307  Royal Challengers Bangalore  Royal Challengers Bangalore
 222308  Royal Challengers Bangalore  Royal Challengers Bangalore
 222309  Royal Challengers Bangalore  Royal Challengers Bangalore
 222310  Royal Challengers Bangalore  Royal Challengers Bangalore

                         Team2   Season                             Venue  \
 0              Gujarat Titans     2022  Narendra Modi Stadium, Ahmedabad
 1              Gujarat Titans     2022  Narendra Modi Stadium, Ahmedabad
 2              Gujarat Titans     2022  Narendra Modi Stadium, Ahmedabad
 3              Gujarat Titans     2022  Narendra Modi Stadium, Ahmedabad
 4              Gujarat Titans     2022  Narendra Modi Stadium, Ahmedabad
 ...                       ...      ...                               ...
 222306  Kolkata Knight Riders  2007/08             M Chinnaswamy Stadium
 222307  Kolkata Knight Riders  2007/08             M Chinnaswamy Stadium
 222308  Kolkata Knight Riders  2007/08             M Chinnaswamy Stadium
 222309  Kolkata Knight Riders  2007/08             M Chinnaswamy Stadium
 222310  Kolkata Knight Riders  2007/08             M Chinnaswamy Stadium

                                              Team1Players  \
 0       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
 1       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
 2       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
 3       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
 4       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
 ...                                                   ...
 222306  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...
 222307  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...
 222308  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...
 222309  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...
 222310  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                              Team2Players
 0       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
 1       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
 2       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
 3       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
 4       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
 ...                                                   ...
 222306  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...
 222307  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...
 222308  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...
 222309  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...
 222310  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...

 [69342 rows x 17 columns],
        Season                                       Venue  \
 0     2007/08                       M Chinnaswamy Stadium
 1     2007/08                       M Chinnaswamy Stadium
 2     2007/08  Punjab Cricket Association Stadium, Mohali
 3     2007/08  Punjab Cricket Association Stadium, Mohali
 4     2007/08                            Feroz Shah Kotla
 ...       ...                                         ...
 1734     2022                                Eden Gardens
 1735     2022            Narendra Modi Stadium, Ahmedabad
 1736     2022            Narendra Modi Stadium, Ahmedabad
 1737     2022            Narendra Modi Stadium, Ahmedabad
 1738     2022            Narendra Modi Stadium, Ahmedabad

                       Team2                        Team1  \
 0     Kolkata Knight Riders  Royal Challengers Bangalore
 1     Kolkata Knight Riders  Royal Challengers Bangalore
 2       Chennai Super Kings                 Punjab Kings
 3       Chennai Super Kings                 Punjab Kings
 4          Rajasthan Royals               Delhi Capitals
 ...                     ...                          ...
 1734   Lucknow Super Giants  Royal Challengers Bangalore
 1735       Rajasthan Royals  Royal Challengers Bangalore
 1736       Rajasthan Royals  Royal Challengers Bangalore
 1737         Gujarat Titans             Rajasthan Royals
 1738         Gujarat Titans             Rajasthan Royals

                       BattingTeam  innings       ID  batsman_run  extras_run  \
 0           Kolkata Knight Riders        1   335982           51          10
 1     Royal Challengers Bangalore        2   335982           19           7
 2             Chennai Super Kings        1   335983           50           3
 3                    Punjab Kings        2   335983           61           2
 4                Rajasthan Royals        1   335984           38           2
 ...                           ...      ...      ...          ...         ...
 1734         Lucknow Super Giants        2  1312198           55           7
 1735  Royal Challengers Bangalore        1  1312199           38           8
 1736             Rajasthan Royals        2  1312199           67           0
 1737             Rajasthan Royals        1  1312200           43           1
 1738               Gujarat Titans        2  1312200           24           7

       PP
 0     61
 1     26
 2     53
 3     63
 4     40
 ...   ..
 1734  62
 1735  46
 1736  67
 1737  44
 1738  31

 [1739 rows x 10 columns],
 <function __main__.bowler_strikerate(batsman, bowler)>,
 <function __main__.stadium_strikerate(batsman, venue)>,
 <function __main__.innings_strikerate(batsman, innings)>,
 <function __main__.score(batsmen, bowlers, venue, innings, battingteam, bowlingteam)>)